modLoader = "javafml"
loaderVersion = "[45,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
    modId = "athena"
    version = "${version}"
    displayName = "Athena"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/athena"
    logoFile = "icon.png"
    authors = "ThatGravyBoat"
    credits = ""
    description = "Crossplatform Baked Model Loader"

[[dependencies.athena]]
    modId = "forge"
    mandatory = true
    versionRange = "[45,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.athena]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4,)"
    ordering = "NONE"
    side = "BOTH"